application:
  title: Microservicios de Productos
  version: 1.0.0
  author: R.PINEDA

server:
  port: 8081
  servlet:
    context-path: /ms-productos/v1/
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.60:1521:xe
    username: MS_PRODUCTOS
    password: 123123
    driver-class-name: oracle.jdbc.driver.OracleDriver